Fix: Use protected on setters
Previously, error CS0200 showed up because subclasses couldn't access
the superclasses private setter methods.

We made those setters `protected` so that the subclasses can now access
them.

Still some errors:

Sedan.cs(10,13): error CS0272: The property or indexer 'Vehicle.Speed'
cannot be used in this context because the set accessor is inaccessible
[/Users/nicholasduckwiler/Repos/prac/csharp-prac/InterfacesInheritance/InterfacesInheritance.csproj]
Sedan.cs(8,16): error CS7036: There is no argument given that
corresponds to the required formal parameter 'speed' of
'Vehicle.Vehicle(double)'
[/Users/nicholasduckwiler/Repos/prac/csharp-prac/InterfacesInheritance/InterfacesInheritance.csproj]
Truck.cs(13,13): error CS0272: The property or indexer 'Vehicle.Speed'
cannot be used in this context because the set accessor is inaccessible
[/Users/nicholasduckwiler/Repos/prac/csharp-prac/InterfacesInheritance/InterfacesInheritance.csproj]
Truck.cs(11,16): error CS7036: There is no argument given that
corresponds to the required formal parameter 'speed' of
'Vehicle.Vehicle(double)'
[/Users/nicholasduckwiler/Repos/prac/csharp-prac/InterfacesInheritance/InterfacesInheritance.csproj]