Issue: Pull duplicate code into Vehicle superclass
This avoids our duplicate code issue because Sedan and Truck now inherit
the previously duplicated members.

This causes a whole bunch of errors:
1. The subclass constructors must call the superclass
constructor (CS7036)
2. The subclass methods cannot access the superclass properties (CS0272
& CS0200)

Sedan.cs(10,13): error CS0272: The property or indexer 'Vehicle.Speed'
cannot be used in this context because the set accessor is inaccessible
[/Users/nicholasduckwiler/Repos/prac/csharp-prac/InterfacesInheritance/InterfacesInheritance.csproj]
Sedan.cs(11,13): error CS0200: Property or indexer
'Vehicle.LicensePlate' cannot be assigned to -- it is read only
[/Users/nicholasduckwiler/Repos/prac/csharp-prac/InterfacesInheritance/InterfacesInheritance.csproj]
Sedan.cs(12,13): error CS0200: Property or indexer 'Vehicle.Wheels'
cannot be assigned to -- it is read only
[/Users/nicholasduckwiler/Repos/prac/csharp-prac/InterfacesInheritance/InterfacesInheritance.csproj]
Sedan.cs(8,16): error CS7036: There is no argument given that
corresponds to the required formal parameter 'speed' of
'Vehicle.Vehicle(double)'
[/Users/nicholasduckwiler/Repos/prac/csharp-prac/InterfacesInheritance/InterfacesInheritance.csproj]
Truck.cs(13,13): error CS0272: The property or indexer 'Vehicle.Speed'
cannot be used in this context because the set accessor is inaccessible
[/Users/nicholasduckwiler/Repos/prac/csharp-prac/InterfacesInheritance/InterfacesInheritance.csproj]
Truck.cs(14,13): error CS0200: Property or indexer
'Vehicle.LicensePlate' cannot be assigned to -- it is read only
[/Users/nicholasduckwiler/Repos/prac/csharp-prac/InterfacesInheritance/InterfacesInheritance.csproj]
Truck.cs(19,17): error CS0200: Property or indexer 'Vehicle.Wheels'
cannot be assigned to -- it is read only
[/Users/nicholasduckwiler/Repos/prac/csharp-prac/InterfacesInheritance/InterfacesInheritance.csproj]
Truck.cs(23,17): error CS0200: Property or indexer 'Vehicle.Wheels'
cannot be assigned to -- it is read only
[/Users/nicholasduckwiler/Repos/prac/csharp-prac/InterfacesInheritance/InterfacesInheritance.csproj]
Truck.cs(11,16): error CS7036: There is no argument given that
corresponds to the required formal parameter 'speed' of
'Vehicle.Vehicle(double)'
[/Users/nicholasduckwiler/Repos/prac/csharp-prac/InterfacesInheritance/InterfacesInheritance.csproj]