Fix2: Switch private to protected
Previously error CS0272 meant that Speed wasn't accessible by subclasses
because it was private.

We fixed that by making it `protected`.

Remaining errors:

Sedan.cs(8,16): error CS7036: There is no argument given that
corresponds to the required formal parameter 'speed' of
'Vehicle.Vehicle(double)'
[/Users/nicholasduckwiler/Repos/prac/csharp-prac/InterfacesInheritance/InterfacesInheritance.csproj]
Truck.cs(11,16): error CS7036: There is no argument given that
corresponds to the required formal parameter 'speed' of
'Vehicle.Vehicle(double)'
[/Users/nicholasduckwiler/Repos/prac/csharp-prac/InterfacesInheritance/InterfacesInheritance.csproj]